#!/bin/bash
current_layout=$(setxkbmap -query | grep layout | awk '{print $2}')
if [ "$current_layout" = "us" ]; then
    setxkbmap se
    notify-send "Keyboard Layout" "Switched to Swedish (SE)"
else
    setxkbmap us
    notify-send "Keyboard Layout" "Switched to US"
fi
